(* Handmade Grammar Natrix *)

id ::= string;

const ::= int
        | bool;

        (* não esquecer maxint e minint*)

expr ::=  const
        | id
        | expr 
        | binop * expr * expr;  
        
        (* constante *)
        (* variável *)
        (* Negar a expressao *)
        (* ADD, SUB, MUL, DIV *)
        
statement ::= expr
            | id * expr
            | id * typ * expr
            | expr * statement * statement
            | id * range * statement;

            (* atribuição *)
            (* print, return *)
            (* declarar e inicializar variável *)

program ::= statement list;
